### ISSUE TITLE
mettre le host « libertempo » dans /etc/hosts

### ISSUE THREAD

**Issue by Prytoegrian** [Libertempo/libertempo-docker#18]
Dès lors où on doit contacter l'API, `curl` fait son office. Mais en mode dev dans le docker, pour que l'hôte soit accessible, il est nécessaire de mettre le DNS dans le `/etc/hosts` en alias de localhost.

**Comment by wouldsmina** [comment]
Ce n'est pas plutôt dans le `/etc/hosts` sur le poste client plutôt que dans le docker??

**Comment by Prytoegrian** [comment]
Non, le site tourne dans le docker et la lib php curl s'appuie sur le système pour résoudre ses dns. Quand tu es en mode dev, l'url n'existe pas et comme le système ne surcharge pas, ça fait des chocapics. Ça et le fait que j'avais déjà une nouvelle ligne dans le client depuis un bail :-)
