### ISSUE TITLE
run.sh : passer le chemin en paramètre

### ISSUE THREAD

**Issue by wouldsmina** [Libertempo/libertempo-docker#25]
Plutôt que de devoir modifier le script run.sh pour y intégrer le chemin des sources du docker, je propose de passer le chemin en paramètre. Dans le cas ou l'utilisateur exécute le script sans paramètre, un message devra l'y inviter...

**Comment by Prytoegrian** [comment]
Ça manque de souplesse à mon goût. Le fait de copier les fichiers de build et de run te permet de mettre toutes les options que tu veux, pour créer ta propre tambouille (ajouter un nouveau point de montage, changer des options). Si on passe par paramètre, ça contraint le dev du fichier à penser à tous ces cas.

**Comment by wouldsmina** [comment]
okay, alors on laisse comme ça :see_no_evil:
